### ISSUE TITLE
Powershell window closes when running Invoke-SelfSearch -Mailbox

### ISSUE THREAD

**Issue by Unimatrix0** [dafthack/MailSniper#35]
If I run ```Invoke-SelfSearch -Mailbox myusername@domain```, I start to get results, and then the powershell window closes.

**Comment by dafthack** [comment]
Yeah both Invoke-SelfSearch and Invoke-GlobalMailSearch will exit out of the PowerShell process when they have completed. The reason for that is it is a temporary fix for issue #1 https://github.com/dafthack/MailSniper/issues/1. Basically, the process keeps a handle on the EWS dll until it is closed out. Going to close this since it is a residual effect of issue #1.

**Comment by Unimatrix0** [comment]
The problem with that solution is you lose the output if you don't output to CSV.
I added the following 2 lines before the fix you added to solve this.
`  Write-Output "Search complete: Press any key to close this window and unload the EWS DLL."`
`  $x = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")`

**Comment by dafthack** [comment]
Ahh I see what you mean. I've been pretty much exclusively running from within a standard command terminal window so when the PowerShell process ended I could still see the results. I like your solution though. Thanks!
